version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
      - API_MODEL=${API_MODEL}
      - WHISPER_MODEL=${WHISPER_MODEL}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped 