version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
      - API_MODEL=${API_MODEL}
      - WHISPER_MODEL=${WHISPER_MODEL}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    restart: unless-stopped 