version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
      - API_MODEL=${API_MODEL}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 